[package]
name = "cornish-server"
version = "0.1.0"
authors = ["Rohan Mishra <rohanmishra2017@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
tokio = { version = "1", features = ["full"] }

